networks:
  levai_network:
    driver: bridge

volumes:
  levai-data:
    driver: local
  levai-models:
    driver: local


services:
  levai-database:
    container_name: levai-database
    build:
      context: ./src/database
      dockerfile: Dockerfile
      args:
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
    networks:
      - levai_network
    ports:
      - "5440:5432"
    volumes:
      -  levai-data:/var/lib/postgresql/data
      - ./database/backups:/backups
    restart: always
    env_file:
      - .env
  levai-models:
    image: ollama/ollama
    container_name: levai-models
    networks:
      - levai_network
    ports:
      - "11434:11434"
    restart: always
    volumes:
      - levai-models:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  levai-backend:
    container_name: levai-backend
    build:
      context: ./src/backend/
      dockerfile: Dockerfile
    networks:
      - levai_network
    ports:
      - "8040:8000"
    depends_on:
      - levai-database
      - levai-models
    restart: always
    env_file:
      - .env
  levai-frontend:
    container_name: levai-frontend
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    networks:
      - levai_network
    ports:
      - "3040:3000"
    depends_on:
      - levai-backend
    restart: always
    env_file:
      - .env
  levai-server:
    container_name: levai-server
    build:
      context: ./src/server
      dockerfile: Dockerfile
    networks:
      - levai_network
    ports:
      - "80:80"
    depends_on:
      - levai-backend
      - levai-frontend
    restart: always