networks:
  levai_network:
    driver: bridge

volumes:
  levai-data:
    driver: local
  levai-models:
    driver: local


services:

  levai-server:
    build:
      context: "./src/server/"
      dockerfile: Dockerfile
    container_name: levai-server
    ports:
      - 8087:80
    networks:
      - levai_network

  levai-db:
    build: 
      context: "./src/database/"
      dockerfile: Dockerfile
    container_name: levai-db
    networks:
      - levai_network
    volumes:
      - levai-data:/var/lib/postgresql/data
    
  levai-api:
    build:
      context: "./src/api/"
      dockerfile: Dockerfile
    container_name: levai-api
    networks:
      - levai_network
  
  levai-models:
    image: ollama/ollama
    container_name: levai-models
    networks:
      - levai_network
    volumes:
      - levai-models:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]