from pydantic import (
    Field,
    field_validator
)

from src.schemas.base import BaseSchema


class OllamaResponse(BaseSchema):
    model: str = Field(
        default="deepseek-r1",
        title="Model",
        description="The model used to generate the response.",
        examples=["llava"]
    )
    created_at: str = Field(
        title="Created At",
        description="The date and time when the response was created.",
        examples=["2021-07-27T20:00:00Z"]
    ),
    response: str =  Field(
        title="Response",
        description="The response generated by the model.",
        examples=["I am a llama."]
    )
    done: bool = Field(
        title="Done",
        description="if the answer has been completed",
        examples=[True]
    )
    context: list = Field(
        title="Context",
        description="The context used to generate the response.",
        examples=[["build an AI that can generate text"]]
    ),
    total_duration: int = Field(
        title="Total Duration",
        description="The total duration of the request in milliseconds.",
        examples=[2938432250]
    ),
    load_duration:  int = Field(
        title="Load Duration",
        description="The duration of loading the model in milliseconds.",
        examples=[2559292]
    ),
    prompt_eval_count: int = Field(
        title="Prompt Eval Count",
        description="The number of evaluations of the prompt.",
        examples=[1]
    ),
    prompt_eval_duration: int = Field(
        title="Prompt Eval Duration",
        description="The duration of evaluating the prompt in milliseconds.",
        examples=[2195557000]
        ),
    eval_count: int = Field(
        title="Eval Count",
        description="The number of evaluations of the response.",
        examples=[44]
    ),
    eval_duration: int = Field(
        title="Eval Duration",
        description="The duration of evaluating the response in milliseconds.",
        examples=[736432000]
    )